### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by pengsrc** [davidlanhaibin/qingstor-sdk-csharp#4]
Questions about naming will be discussed here.

**Comment by pengsrc** [comment]
https://github.com/davidlanhaibin/qingstor-sdk-csharp/blob/master/QingStor_SDK_CSharp/Common/Config.cs#L12

``` c#
    // 配置类
    public class CConfig
    {
        public string Host { get; set; }

```

What does `CConfig` stand for? Why not just call it `Config`?

**Comment by davidlanhaibin** [comment]
CConfig stand for Class Config
