### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by pengsrc** [davidlanhaibin/qingstor-sdk-csharp#5]
Typos found in the project will be listed here.

**Comment by pengsrc** [comment]
https://github.com/davidlanhaibin/qingstor-sdk-csharp/blob/master/QingStor_SDK_CSharp/Common/Config.cs#L16

https://github.com/davidlanhaibin/qingstor-sdk-csharp/blob/master/QingStor_SDK_CSharp/Common/ConstDef.cs#L15

`Protoco` => `Protocol`

**Comment by davidlanhaibin** [comment]
Modified
