### ISSUE TITLE
not using git submodule

### ISSUE THREAD

**Issue by pengsrc** [davidlanhaibin/qingstor-sdk-csharp#6]
The following directories should be included as git submodule.

* https://github.com/davidlanhaibin/qingstor-sdk-csharp/tree/master/QingStor_SDK_CSharp_Test/TestFeature
* https://github.com/davidlanhaibin/qingstor-sdk-csharp/tree/master/QingStor_SDK_CSharp/specs/qingstor

**Comment by davidlanhaibin** [comment]
modified
